"""Rust backend for Sigil: lowers a *checked* AST to Rust source.

Design notes:
  * Only checked programs reach this module, so the emitter never validates —
    it relies on the types the checker stamped onto every expression (.ty).
  * Capabilities (Console, Fs) become zero-sized Copy structs: they occupy
    zero bytes at runtime. The entire security model was spent at check time.
  * Contracts compile to real branches today; the 0.3 milestone (SMT proofs)
    will let proven clauses be skipped here entirely.
  * Sigil values are immutable, so Text/List reads compile to .clone() — the
    simple, obviously-correct lowering. Move/borrow optimization is a later
    milestone; rustc's optimizer already removes many of these.
"""

from . import ast_nodes as A
from .errors import SigilError

RUST_TYPES = {
    "Int": "i64",
    "Bool": "bool",
    "Text": "String",
    "Unit": "()",
    "Console": "Console",
    "Fs": "Fs",
}

# Types whose values are cheap Rust Copy types (no .clone() needed on read).
COPY_KINDS = {"Int", "Bool", "Unit", "Console", "Fs"}

PRELUDE = r'''// Generated by sigilc — do not edit. Source of truth is the .sg file.
#![allow(unused_variables, unused_mut, dead_code, unreachable_code,
         unused_parens, non_camel_case_types, unused_imports)]

#[derive(Clone, Copy)]
struct Console;
#[derive(Clone, Copy)]
struct Fs;

fn rt_fault<T>(msg: &str) -> T {
    eprintln!("runtime fault: {}", msg);
    std::process::exit(1);
}

fn rt_contract_fail(msg: &str) {
    eprintln!("contract violation: {}", msg);
    std::process::exit(1);
}

fn rt_print(_c: Console, msg: String) {
    println!("{}", msg);
}

fn rt_read_line(_c: Console) -> String {
    let mut line = String::new();
    if std::io::stdin().read_line(&mut line).is_err() {
        return rt_fault("read_line failed");
    }
    if line.ends_with('\n') {
        line.pop();
        if line.ends_with('\r') {
            line.pop();
        }
    }
    line
}

fn rt_read_file(_fs: Fs, path: String) -> String {
    match std::fs::read_to_string(&path) {
        Ok(text) => text,
        Err(err) => rt_fault(&format!("read_file failed: {}", err)),
    }
}

fn rt_write_file(_fs: Fs, path: String, data: String) {
    if let Err(err) = std::fs::write(&path, data) {
        rt_fault::<()>(&format!("write_file failed: {}", err));
    }
}

fn rt_div(a: i64, b: i64) -> i64 {
    if b == 0 { rt_fault("division by zero") } else { a / b }
}

fn rt_mod(a: i64, b: i64) -> i64 {
    if b == 0 { rt_fault("modulo by zero") } else { a % b }
}

fn rt_index<T: Clone>(xs: &[T], i: i64) -> T {
    if i < 0 || (i as usize) >= xs.len() {
        rt_fault(&format!("index {} out of range for list of length {}",
                          i, xs.len()))
    } else {
        xs[i as usize].clone()
    }
}

fn rt_push<T>(mut xs: Vec<T>, x: T) -> Vec<T> {
    xs.push(x);
    xs
}

fn rt_len_text(s: String) -> i64 {
    s.chars().count() as i64
}

fn rt_str_int(n: i64) -> String {
    n.to_string()
}

fn rt_str_bool(b: bool) -> String {
    (if b { "true" } else { "false" }).to_string()
}
'''


def rust_string(value: str) -> str:
    """Render a Rust string literal."""
    out = ['"']
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20:
            out.append(f"\\u{{{ord(ch):x}}}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def rust_type(ty: A.Type) -> str:
    if ty.kind == "List":
        elem = rust_type(ty.elem) if ty.elem is not None else "i64"
        return f"Vec<{elem}>"
    return RUST_TYPES[ty.kind]


def expr_ty(expr: A.Expr) -> A.Type:
    ty = getattr(expr, "ty", None)
    if ty is None:
        raise SigilError(
            "internal: expression reached the emitter without a checked type; "
            "run the checker before emitting", expr.line, expr.col)
    return ty


class RustEmitter:
    def __init__(self, program: A.Program):
        self.program = program
        self.lines: list[str] = []
        self.depth = 0

    # ------------------------------------------------------------ output

    def emit_line(self, text: str = "") -> None:
        self.lines.append(("    " * self.depth + text) if text else "")

    def emit(self) -> str:
        self.lines = [PRELUDE]
        for fn in self.program.functions:
            self.emit_fn(fn)
            self.emit_line()
        self.emit_entry()
        return "\n".join(self.lines) + "\n"

    # ------------------------------------------------------------ entry point

    def emit_entry(self) -> None:
        main = next((f for f in self.program.functions if f.name == "main"), None)
        if main is None:
            raise SigilError("no 'main' function to build", 0, 0)
        caps = []
        for pname, ptype in main.params:
            if ptype.kind not in ("Console", "Fs"):
                raise SigilError(
                    f"main parameter '{pname}' must be a capability "
                    f"(Console or Fs), got {ptype}", main.line, main.col)
            caps.append(ptype.kind)
        self.emit_line("fn main() {")
        self.emit_line(f"    s_main({', '.join(caps)});")
        self.emit_line("}")

    # ------------------------------------------------------------ functions

    def emit_fn(self, fn: A.FnDecl) -> None:
        params = ", ".join(f"s_{name}: {rust_type(ty)}" for name, ty in fn.params)
        ret = rust_type(fn.ret)
        self.emit_line(f"fn s_{fn.name}({params}) -> {ret} {{")
        self.depth += 1

        for contract in fn.contracts:
            if contract.kind != "requires":
                continue
            cond = self.expr(contract.expr)
            msg = (f"requires clause of '{fn.name}' failed: "
                   f"`{contract.source}` — blame the CALLER")
            self.emit_line(f"if !({cond}) {{ rt_contract_fail({rust_string(msg)}); }}")

        ensures = [c for c in fn.contracts if c.kind == "ensures"]
        is_unit = fn.ret == A.UNIT

        self.emit_line(f"let s__ret: {ret} = (|| -> {ret} {{")
        self.depth += 1
        self.emit_block(fn.body)
        if not is_unit:
            # The checker proved every path returns; this is never reached.
            self.emit_line("unreachable!()")
        self.depth -= 1
        self.emit_line("})();")

        for contract in ensures:
            cond = self.expr(contract.expr)
            msg = (f"ensures clause of '{fn.name}' failed: "
                   f"`{contract.source}` — blame the CALLEE '{fn.name}'")
            self.emit_line(f"if !({cond}) {{ rt_contract_fail({rust_string(msg)}); }}")

        self.emit_line("s__ret")
        self.depth -= 1
        self.emit_line("}")

    # ------------------------------------------------------------ statements

    def emit_block(self, stmts: list[A.Stmt]) -> None:
        for stmt in stmts:
            self.emit_stmt(stmt)

    def emit_stmt(self, stmt: A.Stmt) -> None:
        if isinstance(stmt, A.Let):
            mut = "mut " if stmt.mutable else ""
            ty = rust_type(stmt.declared_type)
            self.emit_line(f"let {mut}s_{stmt.name}: {ty} = {self.expr(stmt.value)};")
        elif isinstance(stmt, A.Assign):
            self.emit_line(f"s_{stmt.name} = {self.expr(stmt.value)};")
        elif isinstance(stmt, A.Return):
            if stmt.value is None:
                self.emit_line("return;")
            else:
                self.emit_line(f"return {self.expr(stmt.value)};")
        elif isinstance(stmt, A.If):
            self.emit_if(stmt)
        elif isinstance(stmt, A.While):
            self.emit_line(f"while {self.expr(stmt.cond)} {{")
            self.depth += 1
            self.emit_block(stmt.body)
            self.depth -= 1
            self.emit_line("}")
        elif isinstance(stmt, A.ExprStmt):
            self.emit_line(f"let _ = {self.expr(stmt.expr)};")
        else:
            raise SigilError(f"internal: unhandled statement "
                             f"{type(stmt).__name__}", stmt.line, stmt.col)

    def emit_if(self, stmt: A.If) -> None:
        self.emit_line(f"if {self.expr(stmt.cond)} {{")
        self.depth += 1
        self.emit_block(stmt.then_body)
        self.depth -= 1
        if stmt.else_body is None:
            self.emit_line("}")
            return
        # else-if chains parse as a single nested If in the else body.
        if len(stmt.else_body) == 1 and isinstance(stmt.else_body[0], A.If):
            self.emit_line("} else " + self.render_else_if(stmt.else_body[0]))
            return
        self.emit_line("} else {")
        self.depth += 1
        self.emit_block(stmt.else_body)
        self.depth -= 1
        self.emit_line("}")

    def render_else_if(self, stmt: A.If) -> str:
        """Inline header for `else if`; body emitted via normal machinery."""
        # Emit as: `if cond {` ... `}` with the leading text glued to `else`.
        # Simplest correct approach: emit the nested if into a sub-emitter.
        sub = RustEmitter(self.program)
        sub.depth = self.depth
        sub.emit_if(stmt)
        rendered = "\n".join(sub.lines)
        # Strip the indentation of the first line; it is glued after "} else ".
        return rendered.lstrip() if rendered else "{}"

    # ------------------------------------------------------------ expressions

    def expr(self, expr: A.Expr) -> str:
        if isinstance(expr, A.IntLit):
            return f"{expr.value}i64"
        if isinstance(expr, A.BoolLit):
            return "true" if expr.value else "false"
        if isinstance(expr, A.TextLit):
            return f"{rust_string(expr.value)}.to_string()"
        if isinstance(expr, A.ListLit):
            items = ", ".join(self.expr(item) for item in expr.items)
            return f"vec![{items}]"
        if isinstance(expr, A.Var):
            name = "s__ret" if expr.name == "result" else f"s_{expr.name}"
            if expr_ty(expr).kind in COPY_KINDS:
                return name
            return f"{name}.clone()"
        if isinstance(expr, A.Index):
            return f"rt_index(&({self.expr(expr.base)}), {self.expr(expr.index)})"
        if isinstance(expr, A.Unary):
            inner = self.expr(expr.operand)
            return f"!({inner})" if expr.op == "not" else f"-({inner})"
        if isinstance(expr, A.Binary):
            return self.binary(expr)
        if isinstance(expr, A.Call):
            return self.call(expr)
        raise SigilError(f"internal: unhandled expression "
                         f"{type(expr).__name__}", expr.line, expr.col)

    def binary(self, expr: A.Binary) -> str:
        left = self.expr(expr.left)
        right = self.expr(expr.right)
        op = expr.op
        if op == "and":
            return f"({left} && {right})"
        if op == "or":
            return f"({left} || {right})"
        if op == "+":
            if expr_ty(expr.left) == A.TEXT:
                return f'format!("{{}}{{}}", {left}, {right})'
            return f"({left} + {right})"
        if op == "/":
            return f"rt_div({left}, {right})"
        if op == "%":
            return f"rt_mod({left}, {right})"
        return f"({left} {op} {right})"

    def call(self, expr: A.Call) -> str:
        name = expr.name
        args = expr.args

        if name == "len":
            arg = args[0]
            if expr_ty(arg) == A.TEXT:
                return f"rt_len_text({self.expr(arg)})"
            if isinstance(arg, A.ListLit) and not arg.items:
                return "0i64"  # `len([])`: nothing for Rust to infer, fold it
            return f"(({self.expr(arg)}).len() as i64)"
        if name == "str":
            arg = args[0]
            ty = expr_ty(arg)
            if ty == A.TEXT:
                return self.expr(arg)
            helper = "rt_str_bool" if ty == A.BOOL else "rt_str_int"
            return f"{helper}({self.expr(arg)})"
        if name == "push":
            return f"rt_push({self.expr(args[0])}, {self.expr(args[1])})"
        if name in ("print", "read_line", "read_file", "write_file"):
            rendered = ", ".join(self.expr(a) for a in args)
            return f"rt_{name}({rendered})"

        rendered = ", ".join(self.expr(a) for a in args)
        return f"s_{name}({rendered})"


def emit_rust(program: A.Program) -> str:
    return RustEmitter(program).emit()
