"""Rust backend for Sigil: lowers a *checked* AST to Rust source.

Design notes:
  * Only checked programs reach this module, so the emitter never validates —
    it relies on the types the checker stamped onto every expression (.ty).
  * Capabilities (Console, Fs) become zero-sized Copy structs: they occupy
    zero bytes at runtime. The entire security model was spent at check time.
  * Contracts compile to real branches today; the 0.3 milestone (SMT proofs)
    will let proven clauses be skipped here entirely.
  * Sigil values are immutable, so Text/List reads compile to .clone() — the
    simple, obviously-correct lowering. Move/borrow optimization is a later
    milestone; rustc's optimizer already removes many of these.
"""

from . import ast_nodes as A
from .errors import SigilError

RUST_TYPES = {
    "Int": "i64",
    "Bool": "bool",
    "Text": "String",
    "Unit": "()",
    "Console": "Console",
    "Fs": "Fs",
}

# Types whose values are cheap Rust Copy types (no .clone() needed on read).
# Fs is NOT here: an attenuated Fs carries its scope (read-only flag, root),
# so it is Clone but not Copy. Console remains zero-sized.
COPY_KINDS = {"Int", "Bool", "Unit", "Console"}

PRELUDE = r'''// Generated by sigilc — do not edit. Source of truth is the .sg file.
#![allow(unused_variables, unused_mut, dead_code, unreachable_code,
         unused_parens, non_camel_case_types, unused_imports,
         unreachable_patterns)]

#[derive(Clone, Copy)]
struct Console;

#[derive(Clone)]
struct Fs {
    can_write: bool,
    root: Option<String>,
}

fn rt_fault<T>(msg: &str) -> T {
    eprintln!("runtime fault: {}", msg);
    std::process::exit(1);
}

fn rt_contract_fail(msg: &str) {
    eprintln!("contract violation: {}", msg);
    std::process::exit(1);
}

fn rt_cap_fault<T>(msg: &str) -> T {
    eprintln!("capability fault: {}", msg);
    std::process::exit(1);
}

fn rt_clean_path_parts(path: &str, what: &str) -> Vec<String> {
    let normalized = path.replace('\\', "/");
    if normalized.starts_with('/')
        || (normalized.len() >= 2 && normalized.as_bytes()[1] == b':')
    {
        return rt_cap_fault(&format!(
            "absolute path '{}' is not permitted {}", path, what));
    }
    let mut parts = Vec::new();
    for comp in normalized.split('/') {
        if comp == ".." {
            return rt_cap_fault(&format!(
                "path '{}' escapes its capability scope", path));
        }
        if comp.is_empty() || comp == "." {
            continue;
        }
        parts.push(comp.to_string());
    }
    parts
}

fn rt_fs_effective(fs: &Fs, path: &str) -> String {
    match &fs.root {
        None => path.to_string(),
        Some(root) => {
            let parts = rt_clean_path_parts(path, "through a scoped Fs");
            format!("{}/{}", root, parts.join("/"))
        }
    }
}

fn rt_read_only(fs: Fs) -> Fs {
    Fs { can_write: false, root: fs.root }
}

fn rt_subdir(fs: Fs, prefix: String) -> Fs {
    let parts = rt_clean_path_parts(&prefix, "as an Fs scope");
    if parts.is_empty() {
        return rt_cap_fault(&format!(
            "'{}' is an empty path; it cannot scope an Fs", prefix));
    }
    let cleaned = parts.join("/");
    let root = match fs.root {
        None => cleaned,
        Some(r) => format!("{}/{}", r, cleaned),
    };
    Fs { can_write: fs.can_write, root: Some(root) }
}

fn rt_print(_c: Console, msg: String) {
    println!("{}", msg);
}

fn rt_read_line(_c: Console) -> String {
    let mut line = String::new();
    if std::io::stdin().read_line(&mut line).is_err() {
        return rt_fault("read_line failed");
    }
    if line.ends_with('\n') {
        line.pop();
        if line.ends_with('\r') {
            line.pop();
        }
    }
    line
}

fn rt_read_file(fs: Fs, path: String) -> String {
    let effective = rt_fs_effective(&fs, &path);
    match std::fs::read_to_string(&effective) {
        Ok(text) => text,
        Err(err) => rt_fault(&format!("read_file failed: {}", err)),
    }
}

fn rt_write_file(fs: Fs, path: String, data: String) {
    if !fs.can_write {
        rt_cap_fault::<()>(&format!(
            "write_file('{}') denied: this Fs capability is read-only", path));
    }
    let effective = rt_fs_effective(&fs, &path);
    if let Some(parent) = std::path::Path::new(&effective).parent() {
        if !parent.as_os_str().is_empty() {
            let _ = std::fs::create_dir_all(parent);
        }
    }
    if let Err(err) = std::fs::write(&effective, data) {
        rt_fault::<()>(&format!("write_file failed: {}", err));
    }
}

fn rt_div(a: i64, b: i64) -> i64 {
    if b == 0 { rt_fault("division by zero") } else { a / b }
}

fn rt_mod(a: i64, b: i64) -> i64 {
    if b == 0 { rt_fault("modulo by zero") } else { a % b }
}

fn rt_index<T: Clone>(xs: &[T], i: i64) -> T {
    if i < 0 || (i as usize) >= xs.len() {
        rt_fault(&format!("index {} out of range for list of length {}",
                          i, xs.len()))
    } else {
        xs[i as usize].clone()
    }
}

fn rt_push<T>(mut xs: Vec<T>, x: T) -> Vec<T> {
    xs.push(x);
    xs
}

fn rt_len_text(s: String) -> i64 {
    s.chars().count() as i64
}

fn rt_str_int(n: i64) -> String {
    n.to_string()
}

fn rt_str_bool(b: bool) -> String {
    (if b { "true" } else { "false" }).to_string()
}
'''


def rust_string(value: str) -> str:
    """Render a Rust string literal."""
    out = ['"']
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20:
            out.append(f"\\u{{{ord(ch):x}}}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def sym(name: str) -> str:
    """Rust identifier component for a (possibly module-qualified) Sigil
    name: 'geometry.area' -> 'geometry__area'. Dots are not valid in Rust
    identifiers; every emitted symbol routes through here. Auditor-facing
    message TEXT (contract blame) keeps the dotted form."""
    return name.replace(".", "__")


def rust_type(ty: A.Type) -> str:
    if ty.kind == "List":
        elem = rust_type(ty.elem) if ty.elem is not None else "i64"
        return f"Vec<{elem}>"
    if ty.kind in ("Record", "Enum"):
        return f"s_{sym(ty.name)}"
    if ty.kind == "Var":
        raise SigilError(
            f"internal: unsubstituted type variable '{ty.name}' reached the "
            f"emitter; monomorphization must replace every type variable", 0, 0)
    return RUST_TYPES[ty.kind]


def mangle_type(ty: A.Type) -> str:
    """One name component of a monomorphized symbol: Int, Text, List_Int,
    List_List_Text, records by their name. Pathological collisions (a record
    literally named 'List_Int') are theoretically possible and accepted for
    now — record names are flat and '_'-joining is unambiguous in practice."""
    if ty.kind == "List":
        # elem None can only come from an all-empty-literal binding, which the
        # checker rejects as uninferable; defend with the Rust default anyway.
        return f"List_{mangle_type(ty.elem) if ty.elem is not None else 'Int'}"
    if ty.kind in ("Record", "Enum"):
        return sym(ty.name)
    return ty.kind


def expr_ty(expr: A.Expr) -> A.Type:
    ty = getattr(expr, "ty", None)
    if ty is None:
        raise SigilError(
            "internal: expression reached the emitter without a checked type; "
            "run the checker before emitting", expr.line, expr.col)
    return ty


class RustEmitter:
    def __init__(self, program: A.Program):
        self.program = program
        self.lines: list[str] = []
        self.depth = 0
        self.fn_name = ""  # for blame in loop invariant messages
        # Monomorphization state. `subst` is the substitution the current
        # function body is being emitted under (empty for non-generic code);
        # `pending`/`instantiated` form the worklist of concrete instantiations
        # of generic functions, deduplicated by (name, mangled type args).
        self.subst: dict[str, A.Type] = {}
        self.fn_decls = {fn.name: fn for fn in program.functions}
        self.instantiated: set[tuple[str, tuple[str, ...]]] = set()
        self.pending: list[tuple[A.FnDecl, dict[str, A.Type]]] = []

    # ------------------------------------------------------------ output

    def emit_line(self, text: str = "") -> None:
        self.lines.append(("    " * self.depth + text) if text else "")

    def emit(self) -> str:
        self.lines = [PRELUDE]
        for enum in self.program.enums:
            self.emit_enum(enum)
            self.emit_line()
        for rec in self.program.records:
            self.emit_record(rec)
            self.emit_line()
        # Generic functions are never emitted as-is: seed with the non-generic
        # functions, then drain the instantiations their bodies demanded.
        # (An uncalled generic function simply produces no code.)
        for fn in self.program.functions:
            if not fn.type_params:
                self.emit_fn(fn, {})
                self.emit_line()
        while self.pending:
            fn, subst = self.pending.pop(0)
            self.emit_fn(fn, subst)
            self.emit_line()
        self.emit_entry()
        return "\n".join(self.lines) + "\n"

    # ------------------------------------------------------------ generics

    def rtype(self, ty: A.Type) -> str:
        """Render a type under the current substitution."""
        return rust_type(A.substitute(ty, self.subst))

    def instance_name(self, name: str, parts: tuple[str, ...]) -> str:
        return (f"s_{sym(name)}__{'_'.join(parts)}" if parts
                else f"s_{sym(name)}")

    # ------------------------------------------------------------ records

    def record_has_capability(self, ty: A.Type,
                              visiting: set[str] | None = None) -> bool:
        if ty.kind in ("Console", "Fs"):
            return True
        if ty.kind == "List":
            return ty.elem is not None and self.record_has_capability(ty.elem, visiting)
        if ty.kind == "Record":
            visiting = visiting or set()
            if ty.name in visiting:
                return False
            visiting.add(ty.name)
            rec = next(r for r in self.program.records if r.name == ty.name)
            return any(self.record_has_capability(ftype, visiting)
                       for _, ftype in rec.fields)
        if ty.kind == "Enum":
            visiting = visiting or set()
            if ty.name in visiting:
                return False
            visiting.add(ty.name)
            enum = next(e for e in self.program.enums if e.name == ty.name)
            return any(self.record_has_capability(ptype, visiting)
                       for _, payloads in enum.variants for ptype in payloads)
        return False

    def emit_record(self, rec: A.RecordDecl) -> None:
        # Records compare by value unless they hold a capability (the checker
        # forbids comparing those, so the derive can be dropped).
        has_cap = any(self.record_has_capability(ftype)
                      for _, ftype in rec.fields)
        derives = "Clone" if has_cap else "Clone, PartialEq"
        self.emit_line(f"#[derive({derives})]")
        self.emit_line(f"struct s_{sym(rec.name)} {{")
        for fname, ftype in rec.fields:
            self.emit_line(f"    s_{sym(fname)}: {rust_type(ftype)},")
        self.emit_line("}")

    def emit_enum(self, enum: A.EnumDecl) -> None:
        # Same equality rule as records: PartialEq only when capability-free.
        has_cap = any(self.record_has_capability(ptype)
                      for _, payloads in enum.variants for ptype in payloads)
        derives = "Clone" if has_cap else "Clone, PartialEq"
        self.emit_line(f"#[derive({derives})]")
        self.emit_line(f"enum s_{sym(enum.name)} {{")
        for vname, payloads in enum.variants:
            if payloads:
                types = ", ".join(rust_type(p) for p in payloads)
                self.emit_line(f"    s_{sym(vname)}({types}),")
            else:
                self.emit_line(f"    s_{sym(vname)},")
        self.emit_line("}")

    # ------------------------------------------------------------ entry point

    def emit_entry(self) -> None:
        main = next((f for f in self.program.functions if f.name == "main"), None)
        if main is None:
            raise SigilError("no 'main' function to build", 0, 0)
        caps = []
        for pname, ptype in main.params:
            if ptype.kind not in ("Console", "Fs"):
                raise SigilError(
                    f"main parameter '{pname}' must be a capability "
                    f"(Console or Fs), got {ptype}", main.line, main.col)
            caps.append("Console" if ptype.kind == "Console"
                        else "Fs { can_write: true, root: None }")
        self.emit_line("fn main() {")
        self.emit_line(f"    s_{sym(main.name)}({', '.join(caps)});")
        self.emit_line("}")

    # ------------------------------------------------------------ functions

    def emit_fn(self, fn: A.FnDecl, subst: dict[str, A.Type]) -> None:
        self.fn_name = fn.name
        self.subst = subst
        parts = tuple(mangle_type(subst[tp]) for tp in fn.type_params)
        params = ", ".join(f"s_{sym(name)}: {self.rtype(ty)}"
                           for name, ty in fn.params)
        ret = self.rtype(fn.ret)
        self.emit_line(f"fn {self.instance_name(fn.name, parts)}({params}) -> {ret} {{")
        self.depth += 1

        for contract in fn.contracts:
            if contract.kind != "requires" or contract.proven:
                continue
            cond = self.expr(contract.expr)
            msg = (f"requires clause of '{fn.name}' failed: "
                   f"`{contract.source}` — blame the CALLER")
            self.emit_line(f"if !({cond}) {{ rt_contract_fail({rust_string(msg)}); }}")

        ensures = [c for c in fn.contracts if c.kind == "ensures"]
        is_unit = fn.ret == A.UNIT

        self.emit_line(f"let s__ret: {ret} = (|| -> {ret} {{")
        self.depth += 1
        self.emit_block(fn.body)
        if not is_unit:
            # The checker proved every path returns; this is never reached.
            self.emit_line("unreachable!()")
        self.depth -= 1
        self.emit_line("})();")

        for contract in ensures:
            if contract.proven:
                continue
            cond = self.expr(contract.expr)
            msg = (f"ensures clause of '{fn.name}' failed: "
                   f"`{contract.source}` — blame the CALLEE '{fn.name}'")
            self.emit_line(f"if !({cond}) {{ rt_contract_fail({rust_string(msg)}); }}")

        self.emit_line("s__ret")
        self.depth -= 1
        self.emit_line("}")

    # ------------------------------------------------------------ statements

    def emit_block(self, stmts: list[A.Stmt]) -> None:
        for stmt in stmts:
            self.emit_stmt(stmt)

    def emit_stmt(self, stmt: A.Stmt) -> None:
        if isinstance(stmt, A.Let):
            mut = "mut " if stmt.mutable else ""
            ty = self.rtype(stmt.declared_type)
            self.emit_line(f"let {mut}s_{sym(stmt.name)}: {ty} = {self.expr(stmt.value)};")
        elif isinstance(stmt, A.Assign):
            self.emit_line(f"s_{sym(stmt.name)} = {self.expr(stmt.value)};")
        elif isinstance(stmt, A.Return):
            if stmt.value is None:
                self.emit_line("return;")
            else:
                self.emit_line(f"return {self.expr(stmt.value)};")
        elif isinstance(stmt, A.If):
            self.emit_if(stmt)
        elif isinstance(stmt, A.While):
            # Unproven invariants keep their runtime checks at every loop
            # head: once before the loop, once at the end of each iteration.
            checks = []
            for inv in stmt.invariants:
                if inv.proven:
                    continue
                cond = self.expr(inv.expr)
                msg = (f"invariant of while loop in '{self.fn_name}' failed: "
                       f"`{inv.source}` — blame the loop")
                checks.append(
                    f"if !({cond}) {{ rt_contract_fail({rust_string(msg)}); }}")
            for check in checks:
                self.emit_line(check)
            self.emit_line(f"while {self.expr(stmt.cond)} {{")
            self.depth += 1
            self.emit_block(stmt.body)
            for check in checks:
                self.emit_line(check)
            self.depth -= 1
            self.emit_line("}")
        elif isinstance(stmt, A.Match):
            self.emit_match(stmt)
        elif isinstance(stmt, A.ExprStmt):
            self.emit_line(f"let _ = {self.expr(stmt.expr)};")
        else:
            raise SigilError(f"internal: unhandled statement "
                             f"{type(stmt).__name__}", stmt.line, stmt.col)

    def emit_match(self, stmt: A.Match) -> None:
        # The scrutinee is ALWAYS parenthesized: Rust forbids struct literals
        # in scrutinee position, and the clone of a Var scrutinee is an
        # arbitrary expression anyway. Sigil's exhaustiveness rules coincide
        # with Rust's (and dead wildcards are rejected), so every arm maps
        # one-to-one. Binders take the payloads by value from the (owned,
        # already-cloned) scrutinee.
        enum_name = stmt.enum_name  # stamped by the checker
        self.emit_line(f"match ({self.expr(stmt.scrutinee)}) {{")
        self.depth += 1
        for arm in stmt.arms:
            if arm.variant is None:
                pattern = "_"
            elif arm.binders:
                binders = ", ".join(f"s_{sym(b)}" for b in arm.binders)
                pattern = f"s_{sym(enum_name)}::s_{sym(arm.variant)}({binders})"
            else:
                pattern = f"s_{sym(enum_name)}::s_{sym(arm.variant)}"
            self.emit_line(f"{pattern} => {{")
            self.depth += 1
            self.emit_block(arm.body)
            self.depth -= 1
            self.emit_line("}")
        self.depth -= 1
        self.emit_line("}")

    def emit_if(self, stmt: A.If) -> None:
        self.emit_line(f"if {self.expr(stmt.cond)} {{")
        self.depth += 1
        self.emit_block(stmt.then_body)
        self.depth -= 1
        if stmt.else_body is None:
            self.emit_line("}")
            return
        # else-if chains parse as a single nested If in the else body.
        if len(stmt.else_body) == 1 and isinstance(stmt.else_body[0], A.If):
            self.emit_line("} else " + self.render_else_if(stmt.else_body[0]))
            return
        self.emit_line("} else {")
        self.depth += 1
        self.emit_block(stmt.else_body)
        self.depth -= 1
        self.emit_line("}")

    def render_else_if(self, stmt: A.If) -> str:
        """Inline header for `else if`; body emitted via normal machinery."""
        # Emit as: `if cond {` ... `}` with the leading text glued to `else`.
        # Simplest correct approach: emit the nested if into a sub-emitter.
        sub = RustEmitter(self.program)
        sub.depth = self.depth
        sub.fn_name = self.fn_name
        # Share monomorphization state: instantiations discovered inside an
        # else-if body must land on the same worklist.
        sub.subst = self.subst
        sub.instantiated = self.instantiated
        sub.pending = self.pending
        sub.emit_if(stmt)
        rendered = "\n".join(sub.lines)
        # Strip the indentation of the first line; it is glued after "} else ".
        return rendered.lstrip() if rendered else "{}"

    # ------------------------------------------------------------ expressions

    def expr(self, expr: A.Expr) -> str:
        if isinstance(expr, A.IntLit):
            return f"{expr.value}i64"
        if isinstance(expr, A.BoolLit):
            return "true" if expr.value else "false"
        if isinstance(expr, A.TextLit):
            return f"{rust_string(expr.value)}.to_string()"
        if isinstance(expr, A.ListLit):
            items = ", ".join(self.expr(item) for item in expr.items)
            return f"vec![{items}]"
        if isinstance(expr, A.Var):
            # A bare nullary variant, stamped by the checker.
            if getattr(expr, "variant_of", None) is not None:
                return f"s_{sym(expr.variant_of)}::s_{sym(expr.name)}"
            name = "s__ret" if expr.name == "result" else f"s_{sym(expr.name)}"
            # The clone decision depends on the SUBSTITUTED type: a T that is
            # Int in this instantiation stays un-cloned; a T that is Text clones.
            if A.substitute(expr_ty(expr), self.subst).kind in COPY_KINDS:
                return name
            return f"{name}.clone()"
        if isinstance(expr, A.RecordLit):
            fields = ", ".join(f"s_{sym(fname)}: {self.expr(fexpr)}"
                               for fname, fexpr in expr.fields)
            return f"s_{sym(expr.name)} {{ {fields} }}"
        if isinstance(expr, A.FieldAccess):
            return f"({self.expr(expr.base)}).s_{sym(expr.field_name)}"
        if isinstance(expr, A.Index):
            return f"rt_index(&({self.expr(expr.base)}), {self.expr(expr.index)})"
        if isinstance(expr, A.Unary):
            inner = self.expr(expr.operand)
            return f"!({inner})" if expr.op == "not" else f"-({inner})"
        if isinstance(expr, A.Binary):
            return self.binary(expr)
        if isinstance(expr, A.Call):
            return self.call(expr)
        raise SigilError(f"internal: unhandled expression "
                         f"{type(expr).__name__}", expr.line, expr.col)

    def binary(self, expr: A.Binary) -> str:
        left = self.expr(expr.left)
        right = self.expr(expr.right)
        op = expr.op
        if op == "and":
            return f"({left} && {right})"
        if op == "or":
            return f"({left} || {right})"
        if op == "+":
            if expr_ty(expr.left) == A.TEXT:
                return f'format!("{{}}{{}}", {left}, {right})'
            return f"({left} + {right})"
        if op == "/":
            if getattr(expr, "div_safe", False):  # divisor proven nonzero
                return f"({left} / {right})"
            return f"rt_div({left}, {right})"
        if op == "%":
            if getattr(expr, "div_safe", False):
                return f"({left} % {right})"
            return f"rt_mod({left}, {right})"
        return f"({left} {op} {right})"

    def call(self, expr: A.Call) -> str:
        name = expr.name
        args = expr.args

        # Variant construction, stamped by the checker.
        if getattr(expr, "variant_of", None) is not None:
            rendered = ", ".join(self.expr(a) for a in args)
            return f"s_{sym(expr.variant_of)}::s_{sym(name)}({rendered})"

        if name == "len":
            arg = args[0]
            if expr_ty(arg) == A.TEXT:
                return f"rt_len_text({self.expr(arg)})"
            if isinstance(arg, A.ListLit) and not arg.items:
                return "0i64"  # `len([])`: nothing for Rust to infer, fold it
            return f"(({self.expr(arg)}).len() as i64)"
        if name == "str":
            arg = args[0]
            ty = expr_ty(arg)
            if ty == A.TEXT:
                return self.expr(arg)
            helper = "rt_str_bool" if ty == A.BOOL else "rt_str_int"
            return f"{helper}({self.expr(arg)})"
        if name == "push":
            return f"rt_push({self.expr(args[0])}, {self.expr(args[1])})"
        if name in ("print", "read_line", "read_file", "write_file",
                    "read_only", "subdir"):
            rendered = ", ".join(self.expr(a) for a in args)
            return f"rt_{name}({rendered})"

        rendered = ", ".join(self.expr(a) for a in args)

        # A call to a generic function names its concrete instantiation and
        # enqueues it: the checker stamped the bindings (which may mention the
        # enclosing function's type parameters, hence the substitution here).
        callee = self.fn_decls.get(name)
        if callee is not None and callee.type_params:
            stamped = getattr(expr, "type_bindings", None)
            if stamped is None:
                raise SigilError(
                    "internal: generic call reached the emitter without "
                    "inferred type bindings; run the checker before emitting",
                    expr.line, expr.col)
            bindings = {tp: A.substitute(ty, self.subst)
                        for tp, ty in stamped.items()}
            parts = tuple(mangle_type(bindings[tp]) for tp in callee.type_params)
            key = (name, parts)
            if key not in self.instantiated:
                self.instantiated.add(key)
                self.pending.append((callee, bindings))
            return f"{self.instance_name(name, parts)}({rendered})"

        return f"s_{sym(name)}({rendered})"


def emit_rust(program: A.Program) -> str:
    return RustEmitter(program).emit()
